#stas_jam:
#    resource: "@StasJamBundle/Resources/config/routing.yml"
#    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
